# Generated by Django 6.0.2 on 2026-02-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=500)),
                ('Subject', models.CharField(max_length=100)),
                ('hours', models.FloatField()),
                ('Date_Studied', models.DateField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Created_at',
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.DeleteModel(
            name='Hours_Studied',
        ),
        migrations.DeleteModel(
            name='Id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
